### ISSUE TITLE
安装的时候出现这样怎么解决哦

### ISSUE THREAD

**Issue by expfukck** [202252197/ChatGPT_JCM#26]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'serve' ]
2 info using npm@6.14.18
3 info using node@v14.21.3
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle chathome@0.1.0~preserve: chathome@0.1.0
6 info lifecycle chathome@0.1.0~serve: chathome@0.1.0
7 verbose lifecycle chathome@0.1.0~serve: unsafe-perm in lifecycle true
8 verbose lifecycle chathome@0.1.0~serve: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/ChatGPT_JCM/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle chathome@0.1.0~serve: CWD: /root/ChatGPT_JCM
10 silly lifecycle chathome@0.1.0~serve: Args: [ '-c', 'vue-cli-service serve' ]
11 silly lifecycle chathome@0.1.0~serve: Returned: code: 134  signal: null
12 info lifecycle chathome@0.1.0~serve: Failed to exec serve script
13 verbose stack Error: chathome@0.1.0 serve: `vue-cli-service serve`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1088:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
14 verbose pkgid chathome@0.1.0
15 verbose cwd /root/ChatGPT_JCM
16 verbose Linux 4.19.0-8-cloud-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "serve"
18 verbose node v14.21.3
19 verbose npm  v6.14.18
20 error code ELIFECYCLE
21 error errno 134
22 error chathome@0.1.0 serve: `vue-cli-service serve`
22 error Exit status 134
23 error Failed at the chathome@0.1.0 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]

**Comment by 202252197** [comment]
cnpm install -g npm-check-updates试试

**Comment by expfukck** [comment]
找到问题了 是内存不足!
